<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>f1f8725f-a26b-482c-835b-5bec63a6f80a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;uthm achievement nav bar 27 Okt&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='module-232']/div/div/p/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>17ac74c5-ad0c-40a0-98c0-4389205e0c76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/images/headers/uthm_achievement_nav_bar_1312_23.png</value>
      <webElementGuid>62628d95-1bf6-4303-8061-7338b307bd14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>uthm achievement nav bar 27 Okt</value>
      <webElementGuid>78ee9d63-e7df-45c2-8499-cb1d0c8758cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>520</value>
      <webElementGuid>0d7c8742-ea71-4c30-ab2a-4885357c7059</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>60</value>
      <webElementGuid>816014ac-f739-4623-ba3f-bcb5dbaa6443</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;module-232&quot;)/div[@class=&quot;uk-margin-remove-last-child custom&quot;]/div[@class=&quot;uk-margin-remove-last-child custom&quot;]/p[1]/a[1]/img[1]</value>
      <webElementGuid>e71537c4-f8a1-44ec-831b-dc46bf596245</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='module-232']/div/div/p/a/img</value>
      <webElementGuid>46ff3357-5a91-49e7-9f73-6fb138f6f877</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='uthm achievement nav bar 27 Okt']</value>
      <webElementGuid>7f63d929-6a20-4aa0-9904-8fce03aeb6d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/a/img</value>
      <webElementGuid>d067b4f8-7adb-4bf4-b9e8-787c67222c37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/images/headers/uthm_achievement_nav_bar_1312_23.png' and @alt = 'uthm achievement nav bar 27 Okt']</value>
      <webElementGuid>ae5b2be5-2a75-4b26-9198-032b05b0949b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
