<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>facilitiy</name>
   <tag></tag>
   <elementGuidId>00b3c72c-8bde-43cf-be26-1b9dc0e77c59</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;combo_facility&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;combo_facility&quot;]</value>
      <webElementGuid>0dde3aea-f304-42d4-b341-247179582d1e</webElementGuid>
   </webElementProperties>
</WebElementEntity>
